#
# Format:
#
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#

production:
  app: knightio
  stack: cedar

#
# production:
#   app: knightio
#   stack: cedar
#   tag: production/*
#   config:
#     BUNDLE_WITHOUT: "development:test"
#     GOOGLE_ANALYTICS: "UA-12345678-1"

# staging:
#   app: knightio-staging
#   stack: cedar
#   config: &default
#     BUNDLE_WITHOUT: "development:test"
#   addons:
#     - pgbackups:auto-week
#     - memcache:5mb
#     - logging:basic
#     - scheduler:standard

# demo:
#   app: awesomeapp-demo
#   config: *default
